<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert(['name' => 'Colombia / Colombia', 'flag' => 'cif-co']);
		DB::table('countries')->insert(['name' => 'México / México', 'flag' => 'cif-mx']);
		DB::table('countries')->insert(['name' => 'Ecuador / Ecuador', 'flag' => 'cif-ec']);
		DB::table('countries')->insert(['name' => 'Paraguay / Paraguay', 'flag' => 'cif-py']);
		DB::table('countries')->insert(['name' => 'Perú / Perú', 'flag' => 'cif-pe']);
		DB::table('countries')->insert(['name' => 'Guatemala / Guatemala', 'flag' => 'cif-gt']);
		DB::table('countries')->insert(['name' => 'Argentina / Argentina', 'flag' => 'cif-ar']);
		DB::table('countries')->insert(['name' => 'Estados Unidos / USA', 'flag' => 'cif-us']);
		DB::table('countries')->insert(['name' => 'España / Spain', 'flag' => 'cif-es']);
		DB::table('countries')->insert(['name' => 'Venezuela / Venezuela', 'flag' => 'cif-ve']);
		DB::table('countries')->insert(['name' => 'Chile/ Chile', 'flag' => 'cif-cl']);
		DB::table('countries')->insert(['name' => 'Panamá / Panama', 'flag' => 'cif-pa']);
		DB::table('countries')->insert(['name' => 'Honduras / Honduras', 'flag' => 'cif-hn']);
		DB::table('countries')->insert(['name' => 'Cuba / Cuba', 'flag' => 'cif-cu']);
		DB::table('countries')->insert(['name' => 'Costa Rica / Costa Rica', 'flag' => 'cif-cr']);
		DB::table('countries')->insert(['name' => 'República Dominicana / Dominican Republic', 'flag' => 'cif-do']);
		DB::table('countries')->insert(['name' => 'Bolivia / Bolivia', 'flag' => 'cif-bo']);
		DB::table('countries')->insert(['name' => 'El Salvador / El Salvador', 'flag' => 'cif-sv']);
		DB::table('countries')->insert(['name' => 'Uruguay / Uruguay', 'flag' => 'cif-uy']);
		DB::table('countries')->insert(['name' => 'Andorra / Andorra', 'flag' => 'cif-ad']);
		DB::table('countries')->insert(['name' => 'Emiratos Árabes Unidos / United Arab Emirates', 'flag' => 'cif-ae']);
		DB::table('countries')->insert(['name' => 'Afganistán / Afganistan', 'flag' => 'cif-af']);
		DB::table('countries')->insert(['name' => 'Antigua y Barbuda', 'flag' => 'cif-ag']);
		DB::table('countries')->insert(['name' => 'Albania / Albania', 'flag' => 'cif-al']);
		DB::table('countries')->insert(['name' => 'Armenia / Armenia', 'flag' => 'cif-am']);
		DB::table('countries')->insert(['name' => 'Angola / Angola', 'flag' => 'cif-ao']);
		DB::table('countries')->insert(['name' => 'Austria / Austria', 'flag' => 'cif-at']);
		DB::table('countries')->insert(['name' => 'Australia / Australia', 'flag' => 'cif-au']);
		DB::table('countries')->insert(['name' => 'Azerbaiyán / Azerbaijan', 'flag' => 'cif-az']);
		DB::table('countries')->insert(['name' => 'Bosnia-Herzegovina / Bosnia Herzegovina', 'flag' => 'cif-ba']);
		DB::table('countries')->insert(['name' => 'Barbados / Barbados', 'flag' => 'cif-bb']);
		DB::table('countries')->insert(['name' => 'Bangladés / Bangladesh', 'flag' => 'cif-bd']);
		DB::table('countries')->insert(['name' => 'Bélgica / Belgium', 'flag' => 'cif-be']);
		DB::table('countries')->insert(['name' => 'Burkina Faso / Burkina faso', 'flag' => 'cif-bf']);
		DB::table('countries')->insert(['name' => 'Bulgaria / Bulgaria', 'flag' => 'cif-bg']);
		DB::table('countries')->insert(['name' => 'Baréin / Bahrain', 'flag' => 'cif-bh']);
		DB::table('countries')->insert(['name' => 'Burundi / Burundi', 'flag' => 'cif-bi']);
		DB::table('countries')->insert(['name' => 'Benín / Benin', 'flag' => 'cif-bj']);
		DB::table('countries')->insert(['name' => 'Brunéi / Brunei', 'flag' => 'cif-bn']);
		DB::table('countries')->insert(['name' => 'Brasil / Brazil', 'flag' => 'cif-br']);
		DB::table('countries')->insert(['name' => 'Bahamas / Bahamas', 'flag' => 'cif-bs']);
		DB::table('countries')->insert(['name' => 'Bután / Bhutan', 'flag' => 'cif-bt']);
		DB::table('countries')->insert(['name' => 'Botsvana / Botsvana', 'flag' => 'cif-bw']);
		DB::table('countries')->insert(['name' => 'Bielorrusia / Belarus', 'flag' => 'cif-by']);
		DB::table('countries')->insert(['name' => 'Belice / Belize', 'flag' => 'cif-bz']);
		DB::table('countries')->insert(['name' => 'Canadá / Canada', 'flag' => 'cif-ca']);
		DB::table('countries')->insert(['name' => 'República Democrática del Congo / Democratic Republic of Congo', 'flag' => 'cif-cd']);
		DB::table('countries')->insert(['name' => 'República Centroafricana / Central African Republic', 'flag' => 'cif-cf']);
		DB::table('countries')->insert(['name' => 'República del Congo / Republic of Congo', 'flag' => 'cif-cg']);
		DB::table('countries')->insert(['name' => 'Suiza / Swiss', 'flag' => 'cif-ch']);
		DB::table('countries')->insert(['name' => 'Costa de Marfil / Ivory Coast', 'flag' => 'cif-ci']);
		DB::table('countries')->insert(['name' => 'Camerún / Cameroon', 'flag' => 'cif-cm']);
		DB::table('countries')->insert(['name' => 'República Popular China / China', 'flag' => 'cif-cn']);
		DB::table('countries')->insert(['name' => 'Cabo Verde / Cape Verde', 'flag' => 'cif-cv']);
		DB::table('countries')->insert(['name' => 'Chipre / Cyprus', 'flag' => 'cif-cy']);
		DB::table('countries')->insert(['name' => 'Chequia / Chequia', 'flag' => 'cif-cz']);
		DB::table('countries')->insert(['name' => 'Alemania / Germany', 'flag' => 'cif-de']);
		DB::table('countries')->insert(['name' => 'Djibouti / Djibouti', 'flag' => 'cif-dj']);
		DB::table('countries')->insert(['name' => 'Dinamarca / Denmark', 'flag' => 'cif-dk']);
		DB::table('countries')->insert(['name' => 'Dominica / Dominica', 'flag' => 'cif-dm']);
		DB::table('countries')->insert(['name' => 'Algeria / Algeria', 'flag' => 'cif-dz']);
		DB::table('countries')->insert(['name' => 'Estonia / Estonia', 'flag' => 'cif-ee']);
		DB::table('countries')->insert(['name' => 'Egipto / Egypt', 'flag' => 'cif-eg']);
		DB::table('countries')->insert(['name' => 'Eritrea / Eritrea', 'flag' => 'cif-er']);
		DB::table('countries')->insert(['name' => 'Etiopía / Ethiopia', 'flag' => 'cif-et']);
		DB::table('countries')->insert(['name' => 'Finlandia / Finland', 'flag' => 'cif-fi']);
		DB::table('countries')->insert(['name' => 'Fiji / Fiji', 'flag' => 'cif-fj']);
		DB::table('countries')->insert(['name' => 'Micronesia / Micronesia', 'flag' => 'cif-fm']);
		DB::table('countries')->insert(['name' => 'Francia / France', 'flag' => 'cif-fr']);
		DB::table('countries')->insert(['name' => 'Gabun / Gabun', 'flag' => 'cif-ga']);
		DB::table('countries')->insert(['name' => 'Reino Unido / UK', 'flag' => 'cif-gb']);
		DB::table('countries')->insert(['name' => 'Granada / Granada', 'flag' => 'cif-gd']);
		DB::table('countries')->insert(['name' => 'Georgia / Georgia', 'flag' => 'cif-ge']);
		DB::table('countries')->insert(['name' => 'Ghana / Ghana', 'flag' => 'cif-gh']);
		DB::table('countries')->insert(['name' => 'Gambia / Gambia', 'flag' => 'cif-gm']);
		DB::table('countries')->insert(['name' => 'Guinea / Guinea', 'flag' => 'cif-gn']);
		DB::table('countries')->insert(['name' => 'Guinea Ecuatorial / Equatorial Guinea', 'flag' => 'cif-gq']);
		DB::table('countries')->insert(['name' => 'Grecia / Greece', 'flag' => 'cif-gr']);
		DB::table('countries')->insert(['name' => 'Guinea-Bissau / Guinea-Bissau', 'flag' => 'cif-gw']);
		DB::table('countries')->insert(['name' => 'Guayana / Guiana', 'flag' => 'cif-gy']);
		DB::table('countries')->insert(['name' => 'Croacia / Croatia', 'flag' => 'cif-hr']);
		DB::table('countries')->insert(['name' => 'Haití / Haiti', 'flag' => 'cif-ht']);
		DB::table('countries')->insert(['name' => 'Hungría / Hungary', 'flag' => 'cif-hu']);
		DB::table('countries')->insert(['name' => 'Indonesia / Indonesia', 'flag' => 'cif-id']);
		DB::table('countries')->insert(['name' => 'Irlanda / Ireland', 'flag' => 'cif-ie']);
		DB::table('countries')->insert(['name' => 'Israel / Israel', 'flag' => 'cif-il']);
		DB::table('countries')->insert(['name' => 'India / India', 'flag' => 'cif-in']);
		DB::table('countries')->insert(['name' => 'Irak / Iraq', 'flag' => 'cif-iq']);
		DB::table('countries')->insert(['name' => 'Irán / Iran', 'flag' => 'cif-ir']);
		DB::table('countries')->insert(['name' => 'Islandia / Iceland', 'flag' => 'cif-is']);
		DB::table('countries')->insert(['name' => 'Italia / Italy', 'flag' => 'cif-it']);
		DB::table('countries')->insert(['name' => 'Jamaica / Jamaica', 'flag' => 'cif-jm']);
		DB::table('countries')->insert(['name' => 'Jordania / Jordan', 'flag' => 'cif-jo']);
		DB::table('countries')->insert(['name' => 'Japón / Japan', 'flag' => 'cif-jp']);
		DB::table('countries')->insert(['name' => 'Kenia / Kenya', 'flag' => 'cif-ke']);
		DB::table('countries')->insert(['name' => 'Kirguistán / Kyrgyzstan', 'flag' => 'cif-kg']);
		DB::table('countries')->insert(['name' => 'Camboya / Cambodia', 'flag' => 'cif-kh']);
		DB::table('countries')->insert(['name' => 'Kiribati / Kiribati', 'flag' => 'cif-ki']);
		DB::table('countries')->insert(['name' => 'Comoras / Comoros', 'flag' => 'cif-km']);
		DB::table('countries')->insert(['name' => 'St. Kitts y Nevis', 'flag' => 'cif-kn']);
		DB::table('countries')->insert(['name' => 'Corea del Norte / North Korea', 'flag' => 'cif-kp']);
		DB::table('countries')->insert(['name' => 'Corea del Sur / South Korea', 'flag' => 'cif-kr']);
		DB::table('countries')->insert(['name' => 'Kuwait / Kuwait', 'flag' => 'cif-kw']);
		DB::table('countries')->insert(['name' => 'Kazajstán / Kazakhstan', 'flag' => 'cif-kz']);
		DB::table('countries')->insert(['name' => 'Laos / Laos', 'flag' => 'cif-la']);
		DB::table('countries')->insert(['name' => 'Líbano / Libano', 'flag' => 'cif-lb']);
		DB::table('countries')->insert(['name' => 'Santa Lucia / St. Lucia', 'flag' => 'cif-lc']);
		DB::table('countries')->insert(['name' => 'Liechtenstein / Liechtenstein', 'flag' => 'cif-li']);
		DB::table('countries')->insert(['name' => 'Sri Lanka / Sri Lanka', 'flag' => 'cif-lk']);
		DB::table('countries')->insert(['name' => 'Liberia / Liberia', 'flag' => 'cif-lr']);
		DB::table('countries')->insert(['name' => 'Lesoto / Lesoto', 'flag' => 'cif-ls']);
		DB::table('countries')->insert(['name' => 'Lituania / Lithuania', 'flag' => 'cif-lt']);
		DB::table('countries')->insert(['name' => 'Luxemburgo / Luxembourg', 'flag' => 'cif-lu']);
		DB::table('countries')->insert(['name' => 'Letonia / Latvia', 'flag' => 'cif-lv']);
		DB::table('countries')->insert(['name' => 'Libia / Libya', 'flag' => 'cif-ly']);
		DB::table('countries')->insert(['name' => 'Marruecos / Morocco', 'flag' => 'cif-ma']);
		DB::table('countries')->insert(['name' => 'Mónaco / Monaco', 'flag' => 'cif-mc']);
		DB::table('countries')->insert(['name' => 'Moldavia / Moldova', 'flag' => 'cif-md']);
		DB::table('countries')->insert(['name' => 'Montenegro / Montenegro', 'flag' => 'cif-me']);
		DB::table('countries')->insert(['name' => 'Madagascar / Madagascar', 'flag' => 'cif-mg']);
		DB::table('countries')->insert(['name' => 'Islas Marshall / Marshall Islands', 'flag' => 'cif-mh']);
		DB::table('countries')->insert(['name' => 'Macedonia / Macedonia', 'flag' => 'cif-mk']);
		DB::table('countries')->insert(['name' => 'Mali / Mali', 'flag' => 'cif-ml']);
		DB::table('countries')->insert(['name' => 'Myanmar / Myanmar', 'flag' => 'cif-mm']);
		DB::table('countries')->insert(['name' => 'Mongolia / Mongolia', 'flag' => 'cif-mn']);
		DB::table('countries')->insert(['name' => 'Mauritania / Mauritania', 'flag' => 'cif-mr']);
		DB::table('countries')->insert(['name' => 'Malta / Malta', 'flag' => 'cif-mt']);
		DB::table('countries')->insert(['name' => 'República de Mauricio / Republic of Mauritius', 'flag' => 'cif-mu']);
		DB::table('countries')->insert(['name' => 'Maledivas / Maldives', 'flag' => 'cif-mv']);
		DB::table('countries')->insert(['name' => 'Malawi / Malawi', 'flag' => 'cif-mw']);
		DB::table('countries')->insert(['name' => 'Malasia / Malaysia', 'flag' => 'cif-my']);
		DB::table('countries')->insert(['name' => 'Mozambique / Mozambique', 'flag' => 'cif-mz']);
		DB::table('countries')->insert(['name' => 'Namibia / Namibia', 'flag' => 'cif-na']);
		DB::table('countries')->insert(['name' => 'Níger / Niger', 'flag' => 'cif-ne']);
		DB::table('countries')->insert(['name' => 'Nigeria / Nigeria', 'flag' => 'cif-ng']);
		DB::table('countries')->insert(['name' => 'Nicaragua / Nicaragua', 'flag' => 'cif-ni']);
		DB::table('countries')->insert(['name' => 'Países Bajos / Netherlands', 'flag' => 'cif-nl']);
		DB::table('countries')->insert(['name' => 'Noruega / Norway', 'flag' => 'cif-no']);
		DB::table('countries')->insert(['name' => 'Nepal / Nepal', 'flag' => 'cif-np']);
		DB::table('countries')->insert(['name' => 'Nauru / Nauru', 'flag' => 'cif-nr']);
		DB::table('countries')->insert(['name' => 'Niue / Niue', 'flag' => 'cif-nu']);
		DB::table('countries')->insert(['name' => 'Nueva Zelanda / New Zealand', 'flag' => 'cif-nz']);
		DB::table('countries')->insert(['name' => 'Omán / Oman', 'flag' => 'cif-om']);
		DB::table('countries')->insert(['name' => 'Papua Nueva Guinea / Papua Nueva Guinea', 'flag' => 'cif-pg']);
		DB::table('countries')->insert(['name' => 'Filipinas / Philippines', 'flag' => 'cif-ph']);
		DB::table('countries')->insert(['name' => 'Pakistán / Pakistan', 'flag' => 'cif-pk']);
		DB::table('countries')->insert(['name' => 'Polonia / Poland', 'flag' => 'cif-pl']);
		DB::table('countries')->insert(['name' => 'Portugal / Portugal', 'flag' => 'cif-pt']);
		DB::table('countries')->insert(['name' => 'Palau / Palau', 'flag' => 'cif-pw']);
		DB::table('countries')->insert(['name' => 'Katar / Qatar', 'flag' => 'cif-qa']);
		DB::table('countries')->insert(['name' => 'Rumania / Romania', 'flag' => 'cif-ro']);
		DB::table('countries')->insert(['name' => 'Serbia / Serbia', 'flag' => 'cif-rs']);
		DB::table('countries')->insert(['name' => 'Rusia / Russia', 'flag' => 'cif-ru']);
		DB::table('countries')->insert(['name' => 'Ruanda / Rwanda', 'flag' => 'cif-rw']);
		DB::table('countries')->insert(['name' => 'Arabia Saudita / Saudi Arabia', 'flag' => 'cif-sa']);
		DB::table('countries')->insert(['name' => 'Islas Salomón / Solomon Islands', 'flag' => 'cif-sb']);
		DB::table('countries')->insert(['name' => 'Seychelles / Seychelles', 'flag' => 'cif-sc']);
		DB::table('countries')->insert(['name' => 'Sudán / Sudan', 'flag' => 'cif-sd']);
		DB::table('countries')->insert(['name' => 'Suecia / Sweden', 'flag' => 'cif-se']);
		DB::table('countries')->insert(['name' => 'Singapur / Singapore', 'flag' => 'cif-sg']);
		DB::table('countries')->insert(['name' => 'Eslovenia / Slovenia', 'flag' => 'cif-si']);
		DB::table('countries')->insert(['name' => 'Eslovaquia / Slovakia', 'flag' => 'cif-sk']);
		DB::table('countries')->insert(['name' => 'Sierra Leona / Sierra Leone', 'flag' => 'cif-sl']);
		DB::table('countries')->insert(['name' => 'San Marino / San Marino', 'flag' => 'cif-sm']);
		DB::table('countries')->insert(['name' => 'Senegal / Senegal', 'flag' => 'cif-sn']);
		DB::table('countries')->insert(['name' => 'Somalia / Somalia', 'flag' => 'cif-so']);
		DB::table('countries')->insert(['name' => 'Surinam / Surinam', 'flag' => 'cif-sr']);
		DB::table('countries')->insert(['name' => 'Sudán del Sur / South Sudan', 'flag' => 'cif-ss']);
		DB::table('countries')->insert(['name' => 'Santo Tomé y Príncipe / Sao Tome and Principe', 'flag' => 'cif-st']);
		DB::table('countries')->insert(['name' => 'Siria / Syria', 'flag' => 'cif-sy']);
		DB::table('countries')->insert(['name' => 'Swazilandia / Swaziland', 'flag' => 'cif-sz']);
		DB::table('countries')->insert(['name' => 'Chad / Chad', 'flag' => 'cif-td']);
		DB::table('countries')->insert(['name' => 'Togo / Togo', 'flag' => 'cif-tg']);
		DB::table('countries')->insert(['name' => 'Tailandia / Thailand', 'flag' => 'cif-th']);
		DB::table('countries')->insert(['name' => 'Tayikistán / Tayikistán', 'flag' => 'cif-tj']);
		DB::table('countries')->insert(['name' => 'Timor Occidental / Timor', 'flag' => 'cif-tl']);
		DB::table('countries')->insert(['name' => 'Turkmenistán / Turkmenistan', 'flag' => 'cif-tm']);
		DB::table('countries')->insert(['name' => 'Túnez / Tunisia', 'flag' => 'cif-tn']);
		DB::table('countries')->insert(['name' => 'Tonga / Tonga', 'flag' => 'cif-to']);
		DB::table('countries')->insert(['name' => 'Turquía / Turkey', 'flag' => 'cif-tr']);
		DB::table('countries')->insert(['name' => 'Trinidad y Tobago', 'flag' => 'cif-tt']);
		DB::table('countries')->insert(['name' => 'Tuvalu / Tuvalu', 'flag' => 'cif-tv']);
		DB::table('countries')->insert(['name' => 'Taiwán / Taiwan', 'flag' => 'cif-tw']);
		DB::table('countries')->insert(['name' => 'Tanzania / Tanzania', 'flag' => 'cif-tz']);
		DB::table('countries')->insert(['name' => 'Ucrania / Ukraine', 'flag' => 'cif-ua']);
		DB::table('countries')->insert(['name' => 'Uganda / Uganda', 'flag' => 'cif-ug']);
		DB::table('countries')->insert(['name' => 'Uzbekistán / Uzbekistán', 'flag' => 'cif-uz']);
		DB::table('countries')->insert(['name' => 'Ciudad del Vaticano / Vatican City', 'flag' => 'cif-va']);
		DB::table('countries')->insert(['name' => 'St. Vincente y las Granadinas', 'flag' => 'cif-vc']);
		DB::table('countries')->insert(['name' => 'Vietnam / Vietnam', 'flag' => 'cif-vn']);
		DB::table('countries')->insert(['name' => 'Samoa / Samoa', 'flag' => 'cif-ws']);
		DB::table('countries')->insert(['name' => 'Yemen / Yemen', 'flag' => 'cif-ye']);
		DB::table('countries')->insert(['name' => 'Sudáfrica / South Africa', 'flag' => 'cif-za']);
		DB::table('countries')->insert(['name' => 'Zambia / Zambia', 'flag' => 'cif-zm']);
		DB::table('countries')->insert(['name' => 'Zimbabue / Zimbabue', 'flag' => 'cif-zw']);
		DB::table('countries')->insert(['name' => 'Internacional / International', 'flag' => 'cil-globe-alt']);
    }
}
